server:
  port: 5555
 
spring:
  application:
    name: api-gateway
    
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}   
  instance:
    prefer-ip-address: true
      
management:
  endpoints:
    web:
      exposure:
        include: 
        - "routes"