server:
  port: 8081

spring:
  application:
    name: automovel-api

datasource:
    url: jdbc:h2:file:~/automoveldb
    username: sa
    password:
    driverClassName: org.h2.Driver

  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}     
    