server:
  port: 8079
  
spring:
  application:
    name: auth
      
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
      
      
security:
  oauth2:
    resource:
      jwt:
        key-value: 123